### ISSUE TITLE
State Machine split in a separate file

### ISSUE THREAD

**Issue by fcaponetto** [kanje/bosce#15] opened 2022-02-22 10:58 UTC
Hi! I have an issue extracting the structure of a state machine I created by using `boost::statechart`.
Particularly, I split the whole state machine into separate files:

`my_state_machine.h`
`ready.h` <-- state
`active.h` <-- state
`main.cpp`

The files are included as follow:
`main.cpp <-- my_state_machine.h <-- ready.h`
Note: `main.cpp <-- my_state_machine.h` means that `main.cpp` includes `my_state_machine.h`

In the `ready.cpp <-- active.h`

By launching the command:
```
./bosce test_state_machine -s my_state_machine > uml.pu
```
The file generated looks like this:
```
@startuml
[*] --> 2
  state "Ready" as 2 {
  }
@enduml

```
... which clearly does not contain the `Active` state mentioned before.

If I move all the states in a unique file, let's say `my_state_machine.h`, it works as intended.

Willing to provide more details if needed.
Thanks in advance for your help :slightly_smiling_face:

**Comment by kanje** [comment] 2022-02-22 11:08
Hi Fernando! Having a state machine split between different files should work fine. I use is all the time.

States or state machines might be missing if they are not instantiated. In this case a compile just does not include them in the resulting binary. Could you please share the contents of these files and the build command?

**Comment by fcaponetto** [comment] 2022-02-22 11:39
`States or state machines might be missing if they are not instantiated.`
Could you please expand on this?

In my case, the `Ready` state has a `custom_reaction` in it which transitions to the `Active` state. Specifically, `ready.cpp` includes `active.h`

The state machine is built by using `cmake` so, to enable the debug symbols, I added `-DCMAKE_BUILD_TYPE=Debug`.

**Comment by kanje** [comment] 2022-02-22 11:57
> `States or state machines might be missing if they are not instantiated.`
> Could you please expand on this?

What I meant is if you define a state machine or a state but do not use it, e.g. never create an instance of your state machine in the code, it might be missing. A compiler might decide this it is a dead code and remove it. 

That's probably not your case, though, because you have a transition from `Ready` to `Active`. It would be the best if you could attach the code. I will have a look and see where is the problem.

**Comment by fcaponetto** [comment] 2022-02-22 12:08
> What I meant is if you define a state machine or a state but do not use it, e.g. never create an instance of your state machine in the code, it might be missing. A compiler might decide this it is a dead code and remove it.

Ok, got it. However, it's not my case though.
I initialize the state machine in the heap, by using smart pointers:
```
std::shared_ptr<fsm::MyStateMachine> sm = std::make_shared<fsm::MyStateMachine>();
sm->initiate();
```

Also, if I run:
```
./bosce test_state_machine -l
```
I get:
```
Available state-machines:
    fsm::MyStateMachine
```

Unfortunately, as of now, I cannot share the code since contains some IP. Also, it's molded around ROS (Robotic Operating System). Hence, as soon as I'll create a mockup of my design I'll share it here :slightly_smiling_face:

**Comment by kanje** [comment] 2022-02-22 13:57
Thanks!

P.S. If the state machine itself is not an IP, you could do a stripped objdump.
```
bosce -SX binary > stripped.objdump
````
`stripped.objdump` would contain only `boost::statechart` related stuff. This, however, includes names of state machines, states and transitions. As well as code in `custom_reaction`s.

**Comment by fcaponetto** [comment] 2022-02-23 10:16
> P.S. If the state machine itself is not an IP, you could do a stripped objdump.
> 
> ```
> bosce -SX binary > stripped.objdump
> ```

Here is what I get:

```
000000000004c25e <boost::statechart::state_machine<fsm::MyStateMachine, fsm::Ready, std::allocator<void>, boost::statechart::null_exception_translator>::initiate()>:
000000000004d0aa <boost::statechart::state_machine<fsm::MyStateMachine, fsm::Ready, std::allocator<void>, boost::statechart::null_exception_translator>::terminate()>:
000000000004d198 <boost::statechart::state_machine<fsm::MyStateMachine, fsm::Ready, std::allocator<void>, boost::statechart::null_exception_translator>::terminator::terminator(boost::statechart::state_machine<fsm::MyStateMachine, fsm::Ready, std::allocator<void>, boost::statechart::null_exception_translator>&, boost::statechart::event_base const*)>:
000000000004d1e6 <boost::statechart::state_machine<fsm::MyStateMachine, fsm::Ready, std::allocator<void>, boost::statechart::null_exception_translator>::terminator::~terminator()>:
000000000004d22e <boost::statechart::state_machine<fsm::MyStateMachine, fsm::Ready, std::allocator<void>, boost::statechart::null_exception_translator>::initial_construct_function::initial_construct_function(boost::statechart::state_machine<fsm::MyStateMachine, fsm::Ready, std::allocator<void>, boost::statechart::null_exception_translator>&)>:
000000000004d248 <boost::statechart::state_machine<fsm::MyStateMachine, fsm::Ready, std::allocator<void>, boost::statechart::null_exception_translator>::exception_event_handler::exception_event_handler(boost::statechart::state_machine<fsm::MyStateMachine, fsm::Ready, std::allocator<void>, boost::statechart::null_exception_translator>&, boost::statechart::detail::state_base<std::allocator<void>, boost::statechart::detail::rtti_policy>*)>:
000000000004d2d4 <boost::statechart::state_machine<fsm::MyStateMachine, fsm::Ready, std::allocator<void>, boost::statechart::null_exception_translator>::terminator::dismiss()>:
000000000004d2e8 <boost::statechart::state_machine<fsm::MyStateMachine, fsm::Ready, std::allocator<void>, boost::statechart::null_exception_translator>::process_queued_events()>:
000000000004dc44 <boost::statechart::state_machine<fsm::MyStateMachine, fsm::Ready, std::allocator<void>, boost::statechart::null_exception_translator>::terminate_function::terminate_function(boost::statechart::state_machine<fsm::MyStateMachine, fsm::Ready, std::allocator<void>, boost::statechart::null_exception_translator>&)>:
000000000004dcc0 <boost::statechart::state_machine<fsm::MyStateMachine, fsm::Ready, std::allocator<void>, boost::statechart::null_exception_translator>::terminate_impl(bool)>:
000000000004dd4c <boost::statechart::state_machine<fsm::MyStateMachine, fsm::Ready, std::allocator<void>, boost::statechart::null_exception_translator>::initial_construct_function::operator()()>:
000000000004de7a <boost::statechart::state_machine<fsm::MyStateMachine, fsm::Ready, std::allocator<void>, boost::statechart::null_exception_translator>::send_event(boost::statechart::event_base const&)>:
000000000004e93a <boost::statechart::state_machine<fsm::MyStateMachine, fsm::Ready, std::allocator<void>, boost::statechart::null_exception_translator>::terminate_function::operator()()>:
000000000004e998 <boost::statechart::state_machine<fsm::MyStateMachine, fsm::Ready, std::allocator<void>, boost::statechart::null_exception_translator>::terminated() const>:
000000000004e9b0 <boost::statechart::state_machine<fsm::MyStateMachine, fsm::Ready, std::allocator<void>, boost::statechart::null_exception_translator>::terminate_impl(boost::statechart::detail::state_base<std::allocator<void>, boost::statechart::detail::rtti_policy>&, bool)>:
000000000004eb84 <boost::statechart::state_machine<fsm::MyStateMachine, fsm::Ready, std::allocator<void>, boost::statechart::null_exception_translator>::initial_construct()>:
000000000004eeaa <boost::statechart::state_machine<fsm::MyStateMachine, fsm::Ready, std::allocator<void>, boost::statechart::null_exception_translator>::unconsumed_event(boost::statechart::event_base const&)>:
000000000004fa05 <boost::statechart::simple_state<fsm::Ready, fsm::MyStateMachine, boost::mpl::list<mpl_::na>, (boost::statechart::history_mode)0>::initial_deep_construct(boost::statechart::state_machine<fsm::MyStateMachine, fsm::Ready, std::allocator<void>, boost::statechart::null_exception_translator>&)>:
00000000000508ba <boost::statechart::simple_state<fsm::Ready, fsm::MyStateMachine, boost::mpl::list<mpl_::na>, (boost::statechart::history_mode)0>::deep_construct(boost::statechart::state_machine<fsm::MyStateMachine, fsm::Ready, std::allocator<void>, boost::statechart::null_exception_translator>* const&, boost::statechart::state_machine<fsm::MyStateMachine, fsm::Ready, std::allocator<void>, boost::statechart::null_exception_translator>&)>:
00000000000512ab <boost::statechart::simple_state<fsm::Ready, fsm::MyStateMachine, boost::mpl::list<mpl_::na>, (boost::statechart::history_mode)0>::shallow_construct(boost::statechart::state_machine<fsm::MyStateMachine, fsm::Ready, std::allocator<void>, boost::statechart::null_exception_translator>* const&, boost::statechart::state_machine<fsm::MyStateMachine, fsm::Ready, std::allocator<void>, boost::statechart::null_exception_translator>&)>:
0000000000051d26 <boost::statechart::simple_state<fsm::Ready, fsm::MyStateMachine, boost::mpl::list<mpl_::na>, (boost::statechart::history_mode)0>::operator new(unsigned long)>:
0000000000051d40 <boost::statechart::simple_state<fsm::Ready, fsm::MyStateMachine, boost::mpl::list<mpl_::na>, (boost::statechart::history_mode)0>::operator delete(void*)>:
0000000000051de0 <boost::statechart::simple_state<fsm::Ready, fsm::MyStateMachine, boost::mpl::list<mpl_::na>, (boost::statechart::history_mode)0>::set_context(boost::statechart::state_machine<fsm::MyStateMachine, fsm::Ready, std::allocator<void>, boost::statechart::null_exception_translator>* const&)>:
0000000000052482 <boost::statechart::state_machine<fsm::MyStateMachine, fsm::Ready, std::allocator<void>, boost::statechart::null_exception_translator>* boost::get_pointer<boost::statechart::state_machine<fsm::MyStateMachine, fsm::Ready, std::allocator<void>, boost::statechart::null_exception_translator> >(boost::statechart::state_machine<fsm::MyStateMachine, fsm::Ready, std::allocator<void>, boost::statechart::null_exception_translator>*)>:
000000000005256c <boost::statechart::state_machine<fsm::MyStateMachine, fsm::Ready, std::allocator<void>, boost::statechart::null_exception_translator>::add_impl(boost::intrusive_ptr<boost::statechart::detail::leaf_state<std::allocator<void>, boost::statechart::detail::rtti_policy> > const&, boost::statechart::detail::leaf_state<std::allocator<void>, boost::statechart::detail::rtti_policy>&)>:
00000000000526d4 <boost::statechart::simple_state<fsm::Ready, fsm::MyStateMachine, boost::mpl::list<mpl_::na>, (boost::statechart::history_mode)0>::outer_state_ptr() const>:
0000000000052968 <boost::statechart::state_machine<fsm::MyStateMachine, fsm::Ready, std::allocator<void>, boost::statechart::null_exception_translator>::add_inner_state(unsigned char, boost::statechart::detail::state_base<std::allocator<void>, boost::statechart::detail::rtti_policy>*)>:
```

Clearly, there is no track of the `Active` state :slightly_frowning_face:

**Comment by kanje** [comment] 2022-02-23 10:38
It looks like a compiler indeed excludes `Active`. I would need to see the minimal code (C++ and CMake files) which reproduces the issue to see what is happening.

**Comment by fcaponetto** [comment] 2022-02-23 10:57
Thanks for the hint, I believe the crucial part is how I build it.

In my original `CMakeLists.txt`, the `boost::statechart` StateMachine is created as a shared object (so):
``` cmake
add_library(
    fsm
    src/fsm/MyStateMachine.cpp
    src/fsm/Ready.cpp
    src/fsm/Active.cpp
    src/fsm/Anomaly.cpp
)

add_executable(
    ${PROJECT_NAME}
    ...
    src/main.cpp
)

target_link_libraries(
    ${PROJECT_NAME}
   ...
    fsm)
```
... which didn't work as stated above.

However, if move the files from the library (`fsm` in my case) into the executable, the `bosce` works like a charm.
Here is what I practically mean:
``` cmake
add_executable(
    ${PROJECT_NAME}
   ...
    src/fsm/MyStateMachine.cpp
    src/fsm/Ready.cpp
    src/fsm/Active.cpp
    src/fsm/Anomaly.cpp
    src/main.cpp
)
```

**Comment by kanje** [comment] 2022-02-23 13:57
Have you tried running `bosce` on a shared library?

**Comment by fcaponetto** [comment] 2022-02-23 14:09
I am not sure to have properly gotten your suggestion.
In which condition should I run the `bosce` executable?

**Comment by kanje** [comment] 2022-02-23 14:34
You told you compile a state machine as a shared library/object (`.so`). This could explain why some symbols are not included in the main binary. Have you tried something like this?
```
bosce libfsm.so -l
```
I.e. use the library as your input instead of the main binary.

**Comment by fcaponetto** [comment] 2022-02-24 09:47
> You told you compile a state machine as a shared library/object (.so). This could explain why some symbols are not included 
 in the main binary. Have you tried something like this?
> ```
> bosce libfsm.so -l
> ```
If I do so, I'll get **only** the missing part that was not included in the executable.
That's if I do:
```
./bosce test_state_machine -s fsm::MyStateMachine > uml.pu
```
I'll get `MyStateMachine` and the `Ready` state (the `Active` state is missing).

Then, if I type:
```
bosce libfsm.so -s fsm::MyStateMachine > uml.pu
```
I'll get `MyStateMachine` and the `Active` state (the `Ready` state is missing).

Certainly, the issue is caused by how I combined the code. I believe it's not easily solvable unless `bosce` would have a way to accept the executable + the libs involved.
The other solution would be to move the `*cpp` files from the `add_library` section to `add_executable` in the CMakeLists.txt.

**Comment by kanje** [comment] 2022-02-24 09:59
> I believe it's not easily solvable unless bosce would have a way to accept the executable + the libs involved.

This actually can be done. We can allow to specify multiple input files and run [this](https://github.com/kanje/bosce/blob/master/src/main.cpp#L152-L180) in a loop. I will implement it over the weekend.

**Comment by kanje** [comment] 2022-02-27 14:46
Could you please check if https://github.com/kanje/bosce/pull/16 resolves the issue? You can now specify both `test_state_machine` and `libfsm.so` as input files.

Could you please also attach all the sources for `test_state_machine` and `libfsm.so`? You could upload them to a temporary repo, if GitHub does not allow to attach archives. I tried to reproduce it, but I did not manage to get the exact behaviour as you have. I need it to add a unit test.

**Comment by fcaponetto** [comment] 2022-03-01 10:47
Yes, #16 resolves the issue. Moreover, thanks for the effort you put to solve this issue in this open-source project.

Code-wise, as I mentioned before, I am not able to share it because of the IP. :slightly_frowning_face: 
However, when time permits, I can share a simplified version of my actual design.

**Comment by kanje** [comment] 2022-03-01 10:58
Ok, I will then merge #16 and close this issue. If you have time to make a simplified version of your design, please feel free to open a new issue, like "unit test is missing, here is data" :)

**Closed as completed** 2022-03-01 10:58 UTC
